const charactersAndCreatures = [
    "Jewels",
    "Precious Stones",
    "Minerals",
    "Stones",
    "Ancient Stones / Runes / Inscriptions",
    "Trees",
    "Flowers",
    "Plants",
    "Seeds",
    "Old Age",
    "Adult",
    "Young / Teenager",
    "Kid / Boy / Girl",
    "Baby",
    "Neighbour",
    "Friend",
    "Grandfather / Grandmother",
    "Father / Mother",
    "Son / Daughter",
    "Siblings / Twins",
    "Special Powers",
    "Hero",
    "King / Queen",
    "Prince / Princess",
    "God",
    "Mage",
    "Witch",
    "Monster",
    "Mutant",
    "Dwarf",
    "Giant",
    "Ghost / Soul",
    "Warrior / Chevalier",
    "Vampire",
    "Zombie / Dead",
    "Demon",
    "Virus",
    "Robot",
    "Android",
    "Humanoid",
    "Canine",
    "Werewolf",
    "Angel",
    "Humanimal / Wereperson",
    "Feline",
    "Bird",
    "Fish",
    "Shark",
    "Reptiles",
    "Dragons",
    "Dinosaurs",
    "Snakes",
    "Bovines",
    "Bulls",
    "Equines",
    "Unicorn",
    "Pegassus",
    "Fly",
    "Butterfly",
    "Bee",
    "Flying",
    "Insects",
    "Spider",
    "Cockroach / Beetle",
    "Worm",
    "Ant",
    "Zebra",
    "Lama",
    "Exotic Animal",
    "Giraffe",
    "Koala",
    "Panda",
    "Kangaroo",
    "Phoenix",
    "Mythical Animal",
    "Mixture Animal",
    "Chimera",
    "Hydra",
    "Sphinx",
    "Alien",
]

const cultures = [
    "Alien",
    "Ice",
    "Tiki",
    "Inuit",
    "American Native",
    "Aztec",
    "Maya",
    "Anglo-Saxon",
    "Caribbean",
    "Conquistador",
    "French",
    "Sea",
    "Spanish",
    "Viking",
    "Gothic",
    "Rome",
    "Desert",
    "African",
    "Antarctic",
    "Greece",
    "Arabic / Muslim",
    "Soviet",
    "Mesopotamia",
    "India",
    "Russian",
    "China",
    "South East Asian / Thai",
    "Japan",
    "Polynesia",
]

const emotions = [
    "Angry",
    "Sadness",
    "Hate",
    "Disgust",
    "Envy",
    "Apathy",
    "Nostalgic",
    "Confusion",
    "Euphoria",
    "Joy",
    "Surprise",
    "Fear"
]

const historicalPeriods = [
    "Neaderthal",
    "Past",
    "Prehistory",
    "Paleolithic",
    "Neolithic",
    "Bronze Age / Iron Age",
    "Classical Antiquity",
    "Futuristic Past, e.g. Steampunk",
    "Middle Ages",
    "Renaissance",
    "Modern Age",
    "A Particular Day / Hours",
    "Present",
    "Contemporary Age",
    "Retrofuturism",
    "Future",
    "Apocalypse",
    "Post-Apocalypse"
]

const styles = [
    "Megalithic / Stone",
    "Past",
    "Prehistory",
    "Bronze Age / Iron Age/ Metal",
    "Mayan / Aztec",
    "Classic Roman",
    "Classic Greek",
    "Egypt",
    "African",
    "Romanesque",
    "Middle East Empires",
    "Gothic",
    "Japanese",
    "Chinese",
    "Renaissance",
    "Constructivism",
    "Rococo",
    "Dada",
    "Neo-classicism",
    "Surrealism",
    "Cubism",
    "Abstract",
    "Romantic",
    "Symbolism",
    "Impressionism",
    "Avant-garde",
    "Victorian",
    "Art Nouveau",
    "Art Deco",
    "WW2",
    "WW1",
    "40s",
    "50s",
    "Retrofuturism",
    "Pop-Art",
    "60s",
    "Op Art",
    "70s",
    "80s",
    "90s",
    "Retro",
    "Present Day",
    "Y2K",
    "Kitsch",
    "Futuristic",
    "Cool"
]

const genres = [
    "Epic",
    "Drama",
    "Romance",
    "Comedy",
    "Adventure",
    "Fantasy",
    "Science-Fiction",
    "Noir",
    "Thriller",
    "Mystery",
    "Horror",
    "B Series / Serie B",
    "Documentary"
]

const classics = [
    "1984",
    "Divine Comedy",
    "Bible",
    "Moby Dick",
    "Don Quixote",
    "Gilgamesh",
    "The Picture of Dorian Gray",
    "Shakespeare",
    "Odyssey",
    "1001 Nights",
    "Alice in Wonderland",
    "Fairy Tales",
    "Fables",
    "Legends / Folklore"
]

const places = [
    "Ocean",
    "Lake",
    "River",
    "Swimming Pool",
    "Swamp",
    "Heaven",
    "Sky",
    "Mountain",
    "Land",
    "Island",
    "Sea",
    "Undersea",
    "Underground",
    "Hell",
    "Void",
    "Abandoned Place",
    "Pyramid",
    "Temple / Church",
    "Ruins",
    "Cave",
    "Forest",
    "Savannah",
    "Desert",
    "Beach",
    "Ice",
    "Lava",
    "Galaxy",
    "Another Planet",
    "Spaceship",
    "Space Station / Satelite",
    "Airplane",
    "Train",
    "Ferry",
    "Bus",
    "Car",
    "Bike",
    "Bicycle",
    "Planet",
    "Earth",
    "Continent",
    "Country",
    "Metropolis",
    "City",
    "Town",
    "Street",
    "Suburbs",
    "Outskirts",
    "Countryside",
    "Nature",
    "Castle",
    "Palace",
    "Skyscrapper",
    "Building",
    "House",
    "Room",
    "Slum",
    "Farm",
    "Cabin",
    "Roof",
    "Balcony",
    "Living Room",
    "Kitchen",
    "Bathroom",
    "Cellar",
    "Seat of Government",
    "Headquarters",
    "Embassy",
    "Military",
    "Office",
    "School",
    "Museum",
    "Academy",
    "University",
    "Hotel",
    "Gym",
    "Supermarket",
    "Street Market",
    "Flea Market",
    "Laundromat",
    "Library",
    "Gallery",
    "Monument",
    "Square",
    "Graveyard",
    "Shopping Mall",
    "Disco",
    "Bar",
    "Party",
    "Prison",
    "Bank",
    "Police Station",
    "Arcade",
    "Airport",
    "Highway",
    "Road",
    "Way",
    "Bridge",
    "Docks",
    "Train Station",
    "Metro",
    "Stadium/ Arena",
    "Concert Hall",
    "Theatre / Opera House",
    "Cinema",
    "TV Station / Radio Station / Newspaper",
    "Sewers",
    "Cafe",
    "Restaurant",
    "Flower Shop",
    "Park",
    "Zoo",
    "Casino",
    "Races"
]

//need some way to check for dupes 